# Site settings
title: linnesq
email: your-email@domain.com
description: "...because my wordpress is becoming hard to use..."
baseurl: ""
url: "http://linnesq.github.io"

# Build settings
markdown: kramdown
permalink: pretty
