services:
  blog:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./_posts:/app/_posts
      - ./Gemfile:/app/Gemfile
      - ./Gemfile.lock:/app/Gemfile.lock
    ports:
      - 4000:4000
    container_name: blog